import React from 'react';
import type { Metadata } from 'next';
import './globals.css';
import CenterWrapper from '@/components/CenterWrapper/CenterWrapper';
// import { Manrope } from 'next/font/google'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<CenterWrapper>{children}</CenterWrapper>
			</body>
		</html>
	);
}
